package com.fanxing.server.word.auto;

public interface EquipmentWord extends ErrorCode {

	String NAME = "name";

	String NOTES = "notes";

	String SHOWINFO = "showinfo";

	String KEY = "key";

	String EQUIPMENT_LEVEL_MAX = "EQUIPMENT_LEVEL_MAX";

	String EQUIPMENT_EXP_NOT_ENOUGHT = "EQUIPMENT_EXP_NOT_ENOUGHT";

	String ERROR_EQUIPMENT_TEMPLATE_ID = "ERROR_EQUIPMENT_TEMPLATE_ID";

	String ERROR_EQUIPMENT_CHANGE_ID = "ERROR_EQUIPMENT_CHANGE_ID";

	String PART_SERIES_NOT_SUIT = "PART_SERIES_NOT_SUIT";

	String PART_PART_NOT_EXISTS = "PART_PART_NOT_EXISTS";

	String ERROR_NO_RECAST_ATTRIBUTES = "ERROR_NO_RECAST_ATTRIBUTES";

	String ERROR_NO_RARE = "ERROR_NO_RARE";

	String ERROR_NO_SAVE_ATTRIBUTE = "ERROR_NO_SAVE_ATTRIBUTE";

	String ERROR_RECAST_ZERO = "ERROR_RECAST_ZERO";

	String ERROR_REFINING_LIMIT = "ERROR_REFINING_LIMIT";

	String ERROR_BACK_SAVE_MAX = "ERROR_BACK_SAVE_MAX";

	String ERROR_BACK_SIZE_ZERO = "ERROR_BACK_SIZE_ZERO";

	String ERROR_EXTEND_SAVE_MAX = "ERROR_EXTEND_SAVE_MAX";

	String ERROR_EXTEND_ON_TANK = "ERROR_EXTEND_ON_TANK";

	String ERROR_EXTEND_HAVE_REGINING = "ERROR_EXTEND_HAVE_REGINING";

	String ERROR_EXTEND_SOLT_NOT_MATCH = "ERROR_EXTEND_SOLT_NOT_MATCH";

	String ERROR_EQUIPMENT_NULL = "ERROR_EQUIPMENT_NULL";

}
