// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Test.proto

package com.fanxing.server.io.proto.protocol;

public final class TestProtos {
  private TestProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CS_Test1OrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 a = 1;
    boolean hasA();
    int getA();
  }
  public static final class CS_Test1 extends
      com.google.protobuf.GeneratedMessage
      implements CS_Test1OrBuilder {
    // Use CS_Test1.newBuilder() to construct.
    private CS_Test1(Builder builder) {
      super(builder);
    }
    private CS_Test1(boolean noInit) {}
    
    private static final CS_Test1 defaultInstance;
    public static CS_Test1 getDefaultInstance() {
      return defaultInstance;
    }
    
    public CS_Test1 getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fanxing.server.io.proto.protocol.TestProtos.internal_static_CS_Test1_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fanxing.server.io.proto.protocol.TestProtos.internal_static_CS_Test1_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 a = 1;
    public static final int A_FIELD_NUMBER = 1;
    private int a_;
    public boolean hasA() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getA() {
      return a_;
    }
    
    private void initFields() {
      a_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasA()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, a_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, a_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.fanxing.server.io.proto.protocol.TestProtos.CS_Test1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.fanxing.server.io.proto.protocol.TestProtos.CS_Test1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.fanxing.server.io.proto.protocol.TestProtos.CS_Test1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.fanxing.server.io.proto.protocol.TestProtos.CS_Test1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.fanxing.server.io.proto.protocol.TestProtos.CS_Test1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.fanxing.server.io.proto.protocol.TestProtos.CS_Test1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.fanxing.server.io.proto.protocol.TestProtos.CS_Test1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.fanxing.server.io.proto.protocol.TestProtos.CS_Test1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.fanxing.server.io.proto.protocol.TestProtos.CS_Test1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.fanxing.server.io.proto.protocol.TestProtos.CS_Test1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.fanxing.server.io.proto.protocol.TestProtos.CS_Test1 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.fanxing.server.io.proto.protocol.TestProtos.CS_Test1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fanxing.server.io.proto.protocol.TestProtos.internal_static_CS_Test1_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fanxing.server.io.proto.protocol.TestProtos.internal_static_CS_Test1_fieldAccessorTable;
      }
      
      // Construct using com.fanxing.server.io.proto.protocol.TestProtos.CS_Test1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        a_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fanxing.server.io.proto.protocol.TestProtos.CS_Test1.getDescriptor();
      }
      
      public com.fanxing.server.io.proto.protocol.TestProtos.CS_Test1 getDefaultInstanceForType() {
        return com.fanxing.server.io.proto.protocol.TestProtos.CS_Test1.getDefaultInstance();
      }
      
      public com.fanxing.server.io.proto.protocol.TestProtos.CS_Test1 build() {
        com.fanxing.server.io.proto.protocol.TestProtos.CS_Test1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.fanxing.server.io.proto.protocol.TestProtos.CS_Test1 buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.fanxing.server.io.proto.protocol.TestProtos.CS_Test1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.fanxing.server.io.proto.protocol.TestProtos.CS_Test1 buildPartial() {
        com.fanxing.server.io.proto.protocol.TestProtos.CS_Test1 result = new com.fanxing.server.io.proto.protocol.TestProtos.CS_Test1(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.a_ = a_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fanxing.server.io.proto.protocol.TestProtos.CS_Test1) {
          return mergeFrom((com.fanxing.server.io.proto.protocol.TestProtos.CS_Test1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.fanxing.server.io.proto.protocol.TestProtos.CS_Test1 other) {
        if (other == com.fanxing.server.io.proto.protocol.TestProtos.CS_Test1.getDefaultInstance()) return this;
        if (other.hasA()) {
          setA(other.getA());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasA()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              a_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 a = 1;
      private int a_ ;
      public boolean hasA() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getA() {
        return a_;
      }
      public Builder setA(int value) {
        bitField0_ |= 0x00000001;
        a_ = value;
        onChanged();
        return this;
      }
      public Builder clearA() {
        bitField0_ = (bitField0_ & ~0x00000001);
        a_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:CS_Test1)
    }
    
    static {
      defaultInstance = new CS_Test1(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:CS_Test1)
  }
  
  public interface SC_Test1OrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 a = 1;
    boolean hasA();
    int getA();
  }
  public static final class SC_Test1 extends
      com.google.protobuf.GeneratedMessage
      implements SC_Test1OrBuilder {
    // Use SC_Test1.newBuilder() to construct.
    private SC_Test1(Builder builder) {
      super(builder);
    }
    private SC_Test1(boolean noInit) {}
    
    private static final SC_Test1 defaultInstance;
    public static SC_Test1 getDefaultInstance() {
      return defaultInstance;
    }
    
    public SC_Test1 getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fanxing.server.io.proto.protocol.TestProtos.internal_static_SC_Test1_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fanxing.server.io.proto.protocol.TestProtos.internal_static_SC_Test1_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 a = 1;
    public static final int A_FIELD_NUMBER = 1;
    private int a_;
    public boolean hasA() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getA() {
      return a_;
    }
    
    private void initFields() {
      a_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasA()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, a_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, a_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.fanxing.server.io.proto.protocol.TestProtos.SC_Test1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.fanxing.server.io.proto.protocol.TestProtos.SC_Test1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.fanxing.server.io.proto.protocol.TestProtos.SC_Test1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.fanxing.server.io.proto.protocol.TestProtos.SC_Test1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.fanxing.server.io.proto.protocol.TestProtos.SC_Test1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.fanxing.server.io.proto.protocol.TestProtos.SC_Test1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.fanxing.server.io.proto.protocol.TestProtos.SC_Test1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.fanxing.server.io.proto.protocol.TestProtos.SC_Test1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.fanxing.server.io.proto.protocol.TestProtos.SC_Test1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.fanxing.server.io.proto.protocol.TestProtos.SC_Test1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.fanxing.server.io.proto.protocol.TestProtos.SC_Test1 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.fanxing.server.io.proto.protocol.TestProtos.SC_Test1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fanxing.server.io.proto.protocol.TestProtos.internal_static_SC_Test1_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fanxing.server.io.proto.protocol.TestProtos.internal_static_SC_Test1_fieldAccessorTable;
      }
      
      // Construct using com.fanxing.server.io.proto.protocol.TestProtos.SC_Test1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        a_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fanxing.server.io.proto.protocol.TestProtos.SC_Test1.getDescriptor();
      }
      
      public com.fanxing.server.io.proto.protocol.TestProtos.SC_Test1 getDefaultInstanceForType() {
        return com.fanxing.server.io.proto.protocol.TestProtos.SC_Test1.getDefaultInstance();
      }
      
      public com.fanxing.server.io.proto.protocol.TestProtos.SC_Test1 build() {
        com.fanxing.server.io.proto.protocol.TestProtos.SC_Test1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.fanxing.server.io.proto.protocol.TestProtos.SC_Test1 buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.fanxing.server.io.proto.protocol.TestProtos.SC_Test1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.fanxing.server.io.proto.protocol.TestProtos.SC_Test1 buildPartial() {
        com.fanxing.server.io.proto.protocol.TestProtos.SC_Test1 result = new com.fanxing.server.io.proto.protocol.TestProtos.SC_Test1(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.a_ = a_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fanxing.server.io.proto.protocol.TestProtos.SC_Test1) {
          return mergeFrom((com.fanxing.server.io.proto.protocol.TestProtos.SC_Test1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.fanxing.server.io.proto.protocol.TestProtos.SC_Test1 other) {
        if (other == com.fanxing.server.io.proto.protocol.TestProtos.SC_Test1.getDefaultInstance()) return this;
        if (other.hasA()) {
          setA(other.getA());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasA()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              a_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 a = 1;
      private int a_ ;
      public boolean hasA() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getA() {
        return a_;
      }
      public Builder setA(int value) {
        bitField0_ |= 0x00000001;
        a_ = value;
        onChanged();
        return this;
      }
      public Builder clearA() {
        bitField0_ = (bitField0_ & ~0x00000001);
        a_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:SC_Test1)
    }
    
    static {
      defaultInstance = new SC_Test1(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:SC_Test1)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CS_Test1_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CS_Test1_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SC_Test1_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SC_Test1_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nTest.proto\"\025\n\010CS_Test1\022\t\n\001a\030\001 \002(\005\"\025\n\010S" +
      "C_Test1\022\t\n\001a\030\001 \002(\005B2\n$com.fanxing.server" +
      ".io.proto.protocolB\nTestProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_CS_Test1_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_CS_Test1_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CS_Test1_descriptor,
              new java.lang.String[] { "A", },
              com.fanxing.server.io.proto.protocol.TestProtos.CS_Test1.class,
              com.fanxing.server.io.proto.protocol.TestProtos.CS_Test1.Builder.class);
          internal_static_SC_Test1_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_SC_Test1_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SC_Test1_descriptor,
              new java.lang.String[] { "A", },
              com.fanxing.server.io.proto.protocol.TestProtos.SC_Test1.class,
              com.fanxing.server.io.proto.protocol.TestProtos.SC_Test1.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
